### PR TITLE
Introduce --metadata for create-sibling-dataverse

### PR DESCRIPTION
**Pull request by bpoldrack**

### CODE REVIEW

**Comment by bpoldrack** [comment]
Test run cancelled. There are no tests for create-sibling-dataverse yet.

**Comment by mih** [comment]
Here is what I am thinking: We have five mandatory pieces of metadata
- title
- author
- datasetcontact
- dsdescription
- subject

Considering the recursive case: all of this could change for any (sub)dataset. It would be nice to support some kind of templating to be able to tailor things to subdataset. Maybe we could use `foreach-dataset` to do this kind of evaluation. Such a call could execute a combo of metalad-dump, jq or something else to yield the JSON with the expected metadata.

That being said: we could have defaults for everything:
- `title` is the dataset id (plus the relative path to the root dataset when recursing)
- `author` is the author of the last commit
- `datasetcontact` is the person running `create-sibling-dataverse`
- `dsdescription` is a generic summary of this being a datalad dataset and what can be done with it
- `subjects` is "Other"

So the command would have `--metadata` being optional totally optional.

**Comment by bpoldrack** [comment]
How about this:

`--metadata` stays as is for the non-recursive case, but optional.

With `--recursive` the JSON string and `dict` variants become invalid. You can either provide path relative to the dataset's root or a string that's passed to `foreach-dataset` as the `COMMAND`, which can be a to be evaluated python expression or a "regular" call. It's expected to return a dict (`result` field in `foreach`'s result record). All other options to foreach are fixed.
For the defaults we use the same foreach call, with our own function.
That way one can tailor pretty flexibly and the existing foreach substitutions can be utilized.

**Comment by bpoldrack** [comment]
If you agree on this, @mih , we could merge, so all the pieces of the command exist and we can start building some tests for the simple cases (and fixing all the stuff I messed up), while I am implementing that proposal.

**Comment by mih** [comment]
I do not necessarily find this to be the best path forward, but I think this is irrelevant now. Let's merge. Maybe focus on having good metadata defaults for now, and continue to think abot a useful metadata specification pattern.

**Pull request merged**
