### PR TITLE
codespell: config, workflow + fixes

### PR DESCRIPTION
**Pull request by yarikoptic**

### CODE REVIEW

**Comment by mih** [comment]
Hey, thanks for the PR. I will have to leave it hanging here for a bit. There are substantial reorganizations and deletions going on. It already has conflicts, and resolving them cannot have enough priority right now. Sorry.

**Comment by yarikoptic** [comment]
note that actual fixes are just `datalad rerun` away, so the last commit could be dropped and reran easily later.

**Comment by mih** [comment]
Cool, that simplifies things. Thx!

**Comment by yarikoptic** [comment]
I don't think errors in docs and appveyor like 

```
>           raise HTTPError(http_error_msg, response=self)
E           requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://demo.dataverse.org/api/v1/dataverses/dv-b0d40816-5ef4-11ee-af7e-7d5823a458c2/datasets?User-Agent=pydataverse&key=9f08610e-0e99-4b29-b657-9b60536b39c8
../../../dlvenv/lib/python3.8/site-packages/requests/models.py:1021: HTTPError
```
could be related to these changes but I could be proven wrong

**Comment by yarikoptic** [comment]
fwiw - `docs` were red for a few recent runs throughout recent months, so indeed not related

**Comment by adswa** [comment]
Its not your changes from this PR that cause the majority of issues - they upgraded the dataverse version on demo.dataverse.org, and that seemingly contained a few breaking changes. 

We've broken it down this far:

What breaks is the dataverse_dataset fixture, which uses Pydataverse to create a temporary dataset at demo.dataverse.org.
Since 5.14, license metadata is required when creating a dataset via the API: https://github.com/IQSS/dataverse/blob/master/doc/release-notes/5.14-release-notes.md#handling-of-license-information-fixed-in-the-api. Simply adding the necessary metadata like in the diff below does not seem to fix things immediately, though, so there might more.

```diff
diff --git a/datalad_dataverse/tests/utils.py b/datalad_dataverse/tests/utils.py
index 4a0237a..5c6973e 100644
--- a/datalad_dataverse/tests/utils.py
+++ b/datalad_dataverse/tests/utils.py
@@ -104,26 +104,32 @@ def create_test_dataverse_dataset(api, collection, name):
     str
       The persistent DOI for the dataset
     """
-    meta = {
-        "http://purl.org/dc/terms/title": name,
-        "http://purl.org/dc/terms/subject":
-        "Medicine, Health and Life Sciences",
-        "http://purl.org/dc/terms/creator": {
-            "https://dataverse.org/schema/citation/authorName": "DataLad",
-            "https://dataverse.org/schema/citation/authorAffiliation":
-            "datalad.org"
+    meta = {"datasetVersion": {
+        "license": {
+            "name": "CC0 1.0",
+            "uri": "http://creativecommons.org/publicdomain/zero/1.0"
         },
-        "https://dataverse.org/schema/citation/datasetContact": {
-            "https://dataverse.org/schema/citation/datasetContactEmail":
-            "team@datalad.org",
-            "https://dataverse.org/schema/citation/datasetContactName":
-            "DataLad"
-        },
-        "https://dataverse.org/schema/citation/dsDescription": {
-            "https://dataverse.org/schema/citation/dsDescriptionValue":
-            "no description"
-        }
-    }
+        "metadataBlocks": {
+            "http://purl.org/dc/terms/title": name,
+            "http://purl.org/dc/terms/subject":
+            "Medicine, Health and Life Sciences",
+            "http://purl.org/dc/terms/creator": {
+                "https://dataverse.org/schema/citation/authorName": "DataLad",
+                "https://dataverse.org/schema/citation/authorAffiliation":
+                "datalad.org"
+            },
+            "https://dataverse.org/schema/citation/datasetContact": {
+                "https://dataverse.org/schema/citation/datasetContactEmail":
+                "team@datalad.org",
+                "https://dataverse.org/schema/citation/datasetContactName":
+                "DataLad"
+            },
+            "https://dataverse.org/schema/citation/dsDescription": {
+                "https://dataverse.org/schema/citation/dsDescriptionValue":
+                "no description"
+            }
+    }}}
```

**Review by adswa — APPROVED** [review]
looks good to me, thanks!

**Pull request merged**
