### PR TITLE
Reenable testing for windows

### PR DESCRIPTION
**Pull request by mih**
The worst of restructuring is over. Now need to ensure wide compatibility again.

### CODE REVIEW

**Comment by adswa** [comment]
I believe there is a plan to rip out the dependency on the tool that relies on curl, but just to leave a record of the test failure easily accessible:

```
..\tests\test_pydataverse.py::test_file_handling Dataset with pid 'doi:10.70122/FK2/8S1HDQ' created.
curl: (3) unmatched close brace/bracket in URL position 17:
test description}'
                ^
FAILEDDataset {'status': 'OK', 'data': {'message': 'Dataset :persistentId destroyed'}} destroyed
```

```
================================== FAILURES ===================================
_____________________________ test_file_handling ______________________________
tmp_path = WindowsPath('C:/DLTMP/pytest-of-appveyor/pytest-0/test_file_handling0')
dataverse_admin_api = <pyDataverse.api.NativeApi object at 0x00000227DC472280>
dataverse_dataaccess_api = <pyDataverse.api.DataAccessApi object at 0x00000227DC46D610>
dataverse_dataset = 'doi:10.70122/FK2/8S1HDQ'
    def test_file_handling(
            tmp_path,
            dataverse_admin_api,
            dataverse_dataaccess_api,
            dataverse_dataset,
    ):
        # the starting point of `dataverse_dataset` is a freshly
        # created, non-published dataset in draft mode, with no prior
        # version
        fcontent = 'some_content'
        fpath = tmp_path / 'dummy.txt'
        fpath.write_text(fcontent)
        src_md5 = md5sum(fpath)
    
        fileid = check_upload(
            dataverse_admin_api,
            dataverse_dataset, fcontent, fpath, src_md5)
    
        check_download(
            dataverse_dataaccess_api, fileid,
            dataverse_dataset, tmp_path / 'downloaded.txt', src_md5)
    
>       check_file_metadata_update(
            dataverse_admin_api, dataverse_dataset, fileid, fpath)
C:\Python39-x64\lib\site-packages\datalad_dataverse\tests\test_pydataverse.py:39: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Python39-x64\lib\site-packages\datalad_dataverse\tests\test_pydataverse.py:77: in check_file_metadata_update
    _update_md(fileid, {'description': 'test description'}, om['id'])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
fid = 2034270, rec = {'description': 'test description'}, mdid = 1840593
    def _update_md(fid, rec, mdid=None):
        proc = api.update_datafile_metadata(
            fid,
            json_str=json.dumps(rec),
            is_filepid=False,
        )
        # curl ran without error
>       assert proc.returncode == 0
E       assert 3 == 0
E        +  where 3 = CompletedProcess(args='curl -H "X-Dataverse-key: 0e38559c-037d-423a-b87d-7cd304ba8aa5" -X POST -F \'jsonData={"description": "test description"}\' https://demo.dataverse.org/api/v1/files/2034270/metadata', returncode=3, stdout=b'').returncode
```

**Comment by mih** [comment]
Good catch! There are no single quotes on windows.

**Comment by mih** [comment]
Oh nice! That would be #127?

I filed #249 for a second issue pending for the windows tests.

**Comment by adswa** [comment]
98ef6cf wasn't entirely successful - I'm removing the commit and will force-push, but here's a record of the test failures:

<details>

```
E           datalad.runner.exception.CommandError: CommandError: '"git" "-c" "diff.ignoreSubmodules=none" "annex" "testremote" "--fast" "mydv" "-c" "annex.dotfiles=true"' failed with exitcode 1 under C:\DLTMP\pytest-of-appveyor\pytest-0\dataset2 [out: 'testremote mydv (generating test keys...) Remote Tests
E             unavailable remote
E               removeKey:                                       OK (0.02s)
E               storeKey:                                        OK
E               checkPresent:                                    OK
E               retrieveKeyFile:                                 OK (0.02s)
E               retrieveKeyFileCheap:                            OK
E             key size Just 1048576; remote chunksize=0 encryption=none
E               removeKey when not present:                      OK (3.20s)
E               present False:                                   OK (0.15s)
E               storeKey:                                        FAIL
E                 Exception: content not available to send
E                 Use -p '$0=="Remote Tests.key size Just 1048576; remote chunksize=0 encryption=none.storeKey"' to rerun this test only.
E               present True:                                    FAIL
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '$0=="Remote Tests.key size Just 1048576; remote chunksize=0 encryption=none.present True"' to rerun this test only.
E               storeKey when already present:                   FAIL
E                 Exception: content not available to send
E                 Use -p '/key size Just 1048576; remote chunksize=0 encryption=none.storeKey when already present/' to rerun this test only.
E               present True:                                    FAIL
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '$0=="Remote Tests.key size Just 1048576; remote chunksize=0 encryption=none.present True"' to rerun this test only.
E               retrieveKeyFile:                                 FAIL
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '$0=="Remote Tests.key size Just 1048576; remote chunksize=0 encryption=none.retrieveKeyFile"' to rerun this test only.
E               fsck downloaded object:                          OK
E               retrieveKeyFile resume from 0:                   FAIL (0.01s)
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '/key size Just 1048576; remote chunksize=0 encryption=none.retrieveKeyFile resume from 0/' to rerun this test only.
E               fsck downloaded object:                          OK
E               retrieveKeyFile resume from 33%:                 FAIL
E                 Exception: .git\annex\objects\f0a\602\SHA256E-s1048576--9e7f027e257b5660f029690ab9583a06d5e7734426f6122deec9706ccd10ce92.this-is-a-test-key\SHA256E-s1048576--9e7f027e257b5660f029690ab9583a06d5e7734426f6122deec9706ccd10ce92.this-is-a-test-key: openBinaryFile: does not exist (No such file or directory)
E                 Use -p '/key size Just 1048576; remote chunksize=0 encryption=none.retrieveKeyFile resume from 33%/' to rerun this test only.
E               fsck downloaded object:                          OK
E               retrieveKeyFile resume from end:                 FAIL (0.08s)
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '/key size Just 1048576; remote chunksize=0 encryption=none.retrieveKeyFile resume from end/' to rerun this test only.
E               fsck downloaded object:                          OK
E               removeKey when present:                          OK
E               present False:                                   OK
E             key size Just 1048576; remote chunksize=0 encryption=shared
E               removeKey when not present:                      OK (3.15s)
E               present False:                                   OK (0.14s)
E               storeKey:                                        FAIL
E                 Exception: content not available to send
E                 Use -p '$0=="Remote Tests.key size Just 1048576; remote chunksize=0 encryption=shared.storeKey"' to rerun this test only.
E               present True:                                    FAIL
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '$0=="Remote Tests.key size Just 1048576; remote chunksize=0 encryption=shared.present True"' to rerun this test only.
E               storeKey when already present:                   FAIL
E                 Exception: content not available to send
E                 Use -p '/key size Just 1048576; remote chunksize=0 encryption=shared.storeKey when already present/' to rerun this test only.
E               present True:                                    FAIL
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '$0=="Remote Tests.key size Just 1048576; remote chunksize=0 encryption=shared.present True"' to rerun this test only.
E               retrieveKeyFile:                                 FAIL
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '$0=="Remote Tests.key size Just 1048576; remote chunksize=0 encryption=shared.retrieveKeyFile"' to rerun this test only.
E               fsck downloaded object:                          OK
E               retrieveKeyFile resume from 0:                   FAIL (0.03s)
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '/key size Just 1048576; remote chunksize=0 encryption=shared.retrieveKeyFile resume from 0/' to rerun this test only.
E               fsck downloaded object:                          OK
E               retrieveKeyFile resume from 33%:                 FAIL
E                 Exception: .git\annex\objects\f0a\602\SHA256E-s1048576--9e7f027e257b5660f029690ab9583a06d5e7734426f6122deec9706ccd10ce92.this-is-a-test-key\SHA256E-s1048576--9e7f027e257b5660f029690ab9583a06d5e7734426f6122deec9706ccd10ce92.this-is-a-test-key: openBinaryFile: does not exist (No such file or directory)
E                 Use -p '/key size Just 1048576; remote chunksize=0 encryption=shared.retrieveKeyFile resume from 33%/' to rerun this test only.
E               fsck downloaded object:                          OK
E               retrieveKeyFile resume from end:                 FAIL (0.08s)
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '/key size Just 1048576; remote chunksize=0 encryption=shared.retrieveKeyFile resume from end/' to rerun this test only.
E               fsck downloaded object:                          OK
E               removeKey when present:                          OK
E               present False:                                   OK (0.03s)
E             key size Just 1048575; remote chunksize=0 encryption=none
E               removeKey when not present:                      OK
E               present False:                                   OK
E               storeKey:                                        FAIL
E                 Exception: content not available to send
E                 Use -p '$0=="Remote Tests.key size Just 1048575; remote chunksize=0 encryption=none.storeKey"' to rerun this test only.
E               present True:                                    FAIL
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '$0=="Remote Tests.key size Just 1048575; remote chunksize=0 encryption=none.present True"' to rerun this test only.
E               storeKey when already present:                   FAIL
E                 Exception: content not available to send
E                 Use -p '/key size Just 1048575; remote chunksize=0 encryption=none.storeKey when already present/' to rerun this test only.
E               present True:                                    FAIL
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '$0=="Remote Tests.key size Just 1048575; remote chunksize=0 encryption=none.present True"' to rerun this test only.
E               retrieveKeyFile:                                 FAIL
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '$0=="Remote Tests.key size Just 1048575; remote chunksize=0 encryption=none.retrieveKeyFile"' to rerun this test only.
E               fsck downloaded object:                          OK
E               retrieveKeyFile resume from 0:                   FAIL (0.01s)
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '/key size Just 1048575; remote chunksize=0 encryption=none.retrieveKeyFile resume from 0/' to rerun this test only.
E               fsck downloaded object:                          OK
E               retrieveKeyFile resume from 33%:                 FAIL
E                 Exception: .git\annex\objects\2fd\a8c\SHA256E-s1048575--df0f36fc952ae6cd053c6ddb3ab342241fe7c114322bdfebf66713d834f588e9.this-is-a-test-key\SHA256E-s1048575--df0f36fc952ae6cd053c6ddb3ab342241fe7c114322bdfebf66713d834f588e9.this-is-a-test-key: openBinaryFile: does not exist (No such file or directory)
E                 Use -p '/key size Just 1048575; remote chunksize=0 encryption=none.retrieveKeyFile resume from 33%/' to rerun this test only.
E               fsck downloaded object:                          OK
E               retrieveKeyFile resume from end:                 FAIL (0.07s)
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '/key size Just 1048575; remote chunksize=0 encryption=none.retrieveKeyFile resume from end/' to rerun this test only.
E               fsck downloaded object:                          OK
E               removeKey when present:                          OK
E               present False:                                   OK
E             key size Just 1048575; remote chunksize=0 encryption=shared
E               removeKey when not present:                      OK
E               present False:                                   OK
E               storeKey:                                        FAIL
E                 Exception: content not available to send
E                 Use -p '$0=="Remote Tests.key size Just 1048575; remote chunksize=0 encryption=shared.storeKey"' to rerun this test only.
E               present True:                                    FAIL
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '$0=="Remote Tests.key size Just 1048575; remote chunksize=0 encryption=shared.present True"' to rerun this test only.
E               storeKey when already present:                   FAIL
E                 Exception: content not available to send
E                 Use -p '/key size Just 1048575; remote chunksize=0 encryption=shared.storeKey when already present/' to rerun this test only.
E               present True:                                    FAIL
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '$0=="Remote Tests.key size Just 1048575; remote chunksize=0 encryption=shared.present True"' to rerun this test only.
E               retrieveKeyFile:                                 FAIL (0.04s)
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '$0=="Remote Tests.key size Just 1048575; remote chunksize=0 encryption=shared.retrieveKeyFile"' to rerun this test only.
E               fsck downloaded object:                          OK
E               retrieveKeyFile resume from 0:                   FAIL (0.01s)
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '/key size Just 1048575; remote chunksize=0 encryption=shared.retrieveKeyFile resume from 0/' to rerun this test only.
E               fsck downloaded object:                          OK
E               retrieveKeyFile resume from 33%:                 FAIL
E                 Exception: .git\annex\objects\2fd\a8c\SHA256E-s1048575--df0f36fc952ae6cd053c6ddb3ab342241fe7c114322bdfebf66713d834f588e9.this-is-a-test-key\SHA256E-s1048575--df0f36fc952ae6cd053c6ddb3ab342241fe7c114322bdfebf66713d834f588e9.this-is-a-test-key: openBinaryFile: does not exist (No such file or directory)
E                 Use -p '/key size Just 1048575; remote chunksize=0 encryption=shared.retrieveKeyFile resume from 33%/' to rerun this test only.
E               fsck downloaded object:                          OK
E               retrieveKeyFile resume from end:                 FAIL (0.06s)
E                 .\Command\TestRemote.hs:292:
E                 failed
E                 Use -p '/key size Just 1048575; remote chunksize=0 encryption=shared.retrieveKeyFile resume from end/' to rerun this test only.
E               fsck downloaded object:                          OK
E               removeKey when present:                          OK
E               present False:                                   OK
E             exporttree=yes; key size Just 1048576; key size Just 1048575
E               check present export when not present:           OK
E               remove export when not present:                  OK
E               store export:                                    OK
E               check present export after store:                OK
E               store export when already present:               OK
E               retrieve export:                                 OK
E               store new content to export:                     OK
E               check present export after store of new content: OK
E               retrieve export new content:                     OK
E               remove export:                                   OK
E               check present export after remove:               OK
E               retrieve export fails after removal:             OK
E               remove export directory:                         OK
E               remove export directory that is already removed: OK
E             exporttree=yes; key size Just 1048576; key size Just 1048576
E               check present export when not present:           OK
E               remove export when not present:                  OK
E               store export:                                    OK
E               check present export after store:                OK
E               store export when already present:               OK
E               retrieve export:                                 OK
E               store new content to export:                     OK
E               check present export after store of new content: OK
E               retrieve export new content:                     OK
E               remove export:                                   OK
E               check present export after remove:               OK
E               retrieve export fails after removal:             OK
E               remove export directory:                         OK
E               remove export directory that is already removed: OK
E             exporttree=yes; key size Just 1048575; key size Just 1048575
E               check present export when not present:           OK
E               remove export when not present:                  OK
E               store export:                                    OK
E               check present export after store:                OK
E               store export when already present:               OK
E               retrieve export:                                 OK
E               store new content to export:                     OK
E               check present export after store of new content: OK
E               retrieve export new content:                     OK
E               remove export:                                   OK
E               check present export after remove:               OK
E               retrieve export fails after removal:             OK
E               remove export directory:                         OK
E               remove export directory that is already removed: OK
E             exporttree=yes; key size Just 1048575; key size Just 1048576
E               check present export when not present:           OK
E               remove export when not present:                  OK
E               store export:                                    OK
E               check present export after store:                OK
E               store export when already present:               OK
E               retrieve export:                                 OK
E               store new content to export:                     OK
E               check present export after store of new content: OK
E               retrieve export new content:                     OK
E               remove export:                                   OK
E               check present export after remove:               OK
E               retrieve export fails after removal:             OK
E               remove export directory:                         OK
E               remove export directory that is already removed: OK
E           
E           32 out of 125 tests failed (7.27s)
E           failed'] [err: 'Cannot run git-annex-remote-!dne! -- It is not installed in PATH (C:/Program Files/Git/mingw64/libexec/git-core:C:\Program Files\Git\mingw64\bin:C:\Program Files\Git\usr\bin:C:\Users\appveyor\bin:C:\Python39-x64:C:\Python39-x64\Scripts:C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin:C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin:C:\Program Files\Git\cmd:C:\Windows\system32:C:\Windows:C:\Windows\System32\Wbem:C:\Windows\System32\WindowsPowerShell\v1.0\:C:\Windows\System32\OpenSSH\:C:\Program Files\PowerShell\7\:C:\Program Files\7-Zip:C:\Program Files\Microsoft\Web Platform Installer\:C:\Tools\NuGet:C:\Tools\PsTools:C:\Program Files\Git\usr\bin:C:\Program Files\Git LFS:C:\Program Files\Mercurial\:C:\Program Files (x86)\Subversion\bin:C:\Program Files\Docker\Docker\resources\bin:C:\ProgramData\DockerDesktop\version-bin:C:\Program Files\Microsoft SQL Server\130\Tools\Binn\:C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\:C:\Program Files\dotnet\:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin:C:\Tools\xUnit:C:\Tools\xUnit20:C:\Tools\NUnit\bin:C:\Tools\NUnit3\bin:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform:C:\Ruby31\bin:C:\Tools\WebDriver:C:\Python311:C:\Python311\Scripts:C:\Program Files (x86)\nodejs\:C:\Program Files\nodejs:C:\Program Files (x86)\iojs:C:\Program Files\iojs:C:\Users\appveyor\AppData\Roaming\npm:C:\Program Files (x86)\Yarn\bin\:C:\go\bin:C:\Program Files\Java\jdk1.8.0\bin:C:\Program Files\erl10.7\bin:C:\flutter\bin:C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\:C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\:C:\Program Files\Microsoft SQL Server\140\Tools\Binn\:C:\Program Files\Microsoft SQL Server\140\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\:C:\Program Files\Microsoft SQL Server\150\Tools\Binn\:C:\Program Files\Microsoft SQL Server\150\DTS\Binn\:C:\Program Files\Amazon\AWSCLI\bin\:C:\Program Files\Amazon\AWSCLI:C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin:C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\:C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\:C:\Program Files (x86)\Microsoft DirectX SDK:C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code:C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager:C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\:C:\Tools\Doxygen:C:\Tools\Graphviz\bin:C:\Program Files\CMake\bin:C:\ProgramData\chocolatey\bin:C:\Program Files\LLVM\bin:C:\Tools\vcpkg:C:\Tools\Coverity\bin:C:\Program Files (x86)\NSIS:C:\Tools\Octopus:C:\Program Files\Meson\:C:\Program Files (x86)\Apache\Maven\bin:C:\Tools\GitVersion:C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps:C:\Users\appveyor\.dotnet\tools:C:\Users\appveyor\AppData\Roaming\npm:C:\Users\appveyor\AppData\Local\Yarn\bin:C:\Program Files\AppVeyor\BuildAgent\)
E             Cannot run git-annex-remote-!dne! -- It is not installed in PATH (C:/Program Files/Git/mingw64/libexec/git-core:C:\Program Files\Git\mingw64\bin:C:\Program Files\Git\usr\bin:C:\Users\appveyor\bin:C:\Python39-x64:C:\Python39-x64\Scripts:C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin:C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin:C:\Program Files\Git\cmd:C:\Windows\system32:C:\Windows:C:\Windows\System32\Wbem:C:\Windows\System32\WindowsPowerShell\v1.0\:C:\Windows\System32\OpenSSH\:C:\Program Files\PowerShell\7\:C:\Program Files\7-Zip:C:\Program Files\Microsoft\Web Platform Installer\:C:\Tools\NuGet:C:\Tools\PsTools:C:\Program Files\Git\usr\bin:C:\Program Files\Git LFS:C:\Program Files\Mercurial\:C:\Program Files (x86)\Subversion\bin:C:\Program Files\Docker\Docker\resources\bin:C:\ProgramData\DockerDesktop\version-bin:C:\Program Files\Microsoft SQL Server\130\Tools\Binn\:C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\:C:\Program Files\dotnet\:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin:C:\Tools\xUnit:C:\Tools\xUnit20:C:\Tools\NUnit\bin:C:\Tools\NUnit3\bin:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform:C:\Ruby31\bin:C:\Tools\WebDriver:C:\Python311:C:\Python311\Scripts:C:\Program Files (x86)\nodejs\:C:\Program Files\nodejs:C:\Program Files (x86)\iojs:C:\Program Files\iojs:C:\Users\appveyor\AppData\Roaming\npm:C:\Program Files (x86)\Yarn\bin\:C:\go\bin:C:\Program Files\Java\jdk1.8.0\bin:C:\Program Files\erl10.7\bin:C:\flutter\bin:C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\:C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\:C:\Program Files\Microsoft SQL Server\140\Tools\Binn\:C:\Program Files\Microsoft SQL Server\140\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\:C:\Program Files\Microsoft SQL Server\150\Tools\Binn\:C:\Program Files\Microsoft SQL Server\150\DTS\Binn\:C:\Program Files\Amazon\AWSCLI\bin\:C:\Program Files\Amazon\AWSCLI:C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin:C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\:C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\:C:\Program Files (x86)\Microsoft DirectX SDK:C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code:C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager:C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\:C:\Tools\Doxygen:C:\Tools\Graphviz\bin:C:\Program Files\CMake\bin:C:\ProgramData\chocolatey\bin:C:\Program Files\LLVM\bin:C:\Tools\vcpkg:C:\Tools\Coverity\bin:C:\Program Files (x86)\NSIS:C:\Tools\Octopus:C:\Program Files\Meson\:C:\Program Files (x86)\Apache\Maven\bin:C:\Tools\GitVersion:C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps:C:\Users\appveyor\.dotnet\tools:C:\Users\appveyor\AppData\Roaming\npm:C:\Users\appveyor\AppData\Local\Yarn\bin:C:\Program Files\AppVeyor\BuildAgent\)
E             Cannot run git-annex-remote-!dne! -- It is not installed in PATH (C:/Program Files/Git/mingw64/libexec/git-core:C:\Program Files\Git\mingw64\bin:C:\Program Files\Git\usr\bin:C:\Users\appveyor\bin:C:\Python39-x64:C:\Python39-x64\Scripts:C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin:C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\bin:C:\Program Files\Git\cmd:C:\Windows\system32:C:\Windows:C:\Windows\System32\Wbem:C:\Windows\System32\WindowsPowerShell\v1.0\:C:\Windows\System32\OpenSSH\:C:\Program Files\PowerShell\7\:C:\Program Files\7-Zip:C:\Program Files\Microsoft\Web Platform Installer\:C:\Tools\NuGet:C:\Tools\PsTools:C:\Program Files\Git\usr\bin:C:\Program Files\Git LFS:C:\Program Files\Mercurial\:C:\Program Files (x86)\Subversion\bin:C:\Program Files\Docker\Docker\resources\bin:C:\ProgramData\DockerDesktop\version-bin:C:\Program Files\Microsoft SQL Server\130\Tools\Binn\:C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\:C:\Program Files\dotnet\:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\150:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin:C:\Tools\xUnit:C:\Tools\xUnit20:C:\Tools\NUnit\bin:C:\Tools\NUnit3\bin:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform:C:\Ruby31\bin:C:\Tools\WebDriver:C:\Python311:C:\Python311\Scripts:C:\Program Files (x86)\nodejs\:C:\Program Files\nodejs:C:\Program Files (x86)\iojs:C:\Program Files\iojs:C:\Users\appveyor\AppData\Roaming\npm:C:\Program Files (x86)\Yarn\bin\:C:\go\bin:C:\Program Files\Java\jdk1.8.0\bin:C:\Program Files\erl10.7\bin:C:\flutter\bin:C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\:C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\:C:\Program Files\Microsoft SQL Server\140\Tools\Binn\:C:\Program Files\Microsoft SQL Server\140\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\:C:\Program Files\Microsoft SQL Server\150\Tools\Binn\:C:\Program Files\Microsoft SQL Server\150\DTS\Binn\:C:\Program Files\Amazon\AWSCLI\bin\:C:\Program Files\Amazon\AWSCLI:C:\Program Files (x86)\Google\Cloud SDK\google-cloud-sdk\bin:C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\:C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\:C:\Program Files (x86)\Microsoft DirectX SDK:C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code:C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager:C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\:C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\:C:\Tools\Doxygen:C:\Tools\Graphviz\bin:C:\Program Files\CMake\bin:C:\ProgramData\chocolatey\bin:C:\Program Files\LLVM\bin:C:\Tools\vcpkg:C:\Tools\Coverity\bin:C:\Program Files (x86)\NSIS:C:\Tools\Octopus:C:\Program Files\Meson\:C:\Program Files (x86)\Apache\Maven\bin:C:\Tools\GitVersion:C:\Users\appveyor\AppData\Local\Microsoft\WindowsApps:C:\Users\appveyor\.dotnet\tools:C:\Users\appveyor\AppData\Roaming\npm:C:\Users\appveyor\AppData\Local\Yarn\bin:C:\Program Files\AppVeyor\BuildAgent\)
E           cp: cannot stat '.git\annex\objects\f0a\602\SHA256E-s1048576--9e7f027e257b5660f029690ab9583a06d5e7734426f6122deec9706ccd10ce92.this-is-a-test-key\SHA256E-s1048576--9e7f027e257b5660f029690ab9583a06d5e7734426f6122deec9706ccd10ce92.this-is-a-test-key': No such file or directory
E           cp: cannot stat '.git\annex\objects\f0a\602\SHA256E-s1048576--9e7f027e257b5660f029690ab9583a06d5e7734426f6122deec9706ccd10ce92.this-is-a-test-key\SHA256E-s1048576--9e7f027e257b5660f029690ab9583a06d5e7734426f6122deec9706ccd10ce92.this-is-a-test-key': No such file or directory
E           cp: cannot stat '.git\annex\objects\2fd\a8c\SHA256E-s1048575--df0f36fc952ae6cd053c6ddb3ab342241fe7c114322bdfebf66713d834f588e9.this-is-a-test-key\SHA256E-s1048575--df0f36fc952ae6cd053c6ddb3ab342241fe7c114322bdfebf66713d834f588e9.this-is-a-test-key': No such file or directory
E           cp: cannot stat '.git\annex\objects\2fd\a8c\SHA256E-s1048575--df0f36fc952ae6cd053c6ddb3ab342241fe7c114322bdfebf66713d834f588e9.this-is-a-test-key\SHA256E-s1048575--df0f36fc952ae6cd053c6ddb3ab342241fe7c114322bdfebf66713d834f588e9.this-is-a-test-key': No such file or directory
E           testremote: 1 failed']

```
</details>

**Comment by adswa** [comment]
I can't yet get a recent enough git-annex version to try out https://github.com/datalad/datalad-dataverse/commit/98ef6cfcd798e53b39ae1d8125a5c3a97a683b52 again. Even compiling from source only gives me one from February 28th

**Comment by mih** [comment]
Thx @adswa for the analysis!

**Pull request merged**
